/*************************************************************
 *
 * left_attack_1 : Tile and Palette Data For GBA Development
 *
 *   This file was autogenerated by the program 'bmp2gbtile',
 *   written by Matthew Wachowski (mwachowski@hotmail.com)
 *   The bmp2gbtile program is free for non commercial use.
 *   Contact Matthew Wachowski to use bmp2gbtile for
 *   commercial purposes.
 *
 * This file contains data based off the following bitmaps:
 *
 *    0 (   0): left_attack_1.bmp    (16x16, 8 bit, 216 cols, pal 0)
 *
 * The first object index in this file is: 0
 *
 **************************************************************/

/* This value is the number of bitmaps defined in this        */
/* structure, and gives the offset of the first definition    */

extern const unsigned short left_attack_1_bmp_count;
extern const unsigned short left_attack_1_tile_offset;

/* These values can be used to set up OBJ structures          */
/* with tile data referred to in this file                    */
/* (this assumes that the tile data is loaded into            */
/* OBJ Ram on the GBA at the correct offset)                  */

extern const unsigned short left_attack_1_attr0_and_mask;
extern const unsigned short left_attack_1_attr1_and_mask;
extern const unsigned short left_attack_1_attr2_and_mask;
extern const unsigned short left_attack_1_attr0_or_mask[1];
extern const unsigned short left_attack_1_attr1_or_mask[1];
extern const unsigned short left_attack_1_attr2_or_mask[1];

/* This value gives color palette definitions                 */
/* for all defined palettes                                   */

extern const unsigned short left_attack_1_palette_count;
extern const unsigned short left_attack_1_palette_data[0x1C0];

/* This value gives the size of the tile data                 */
/* structure and values for the tile entrys                   */

extern const unsigned short left_attack_1_tile_byte_count;
extern const unsigned char left_attack_1_tile_data[0x0100];

/************************************************************/

