############################################################
# A Simple Makefile for bmp2gbtile
#
# Matthew Wachowski
############################################################

CXX = g++
CFLAGS = -O2

bmp2gbtile: bmp2gbtile.cpp bmp2gbtile.hpp
	$(CXX) -o bmp2gbtile $(CFLAGS) bmp2gbtile.cpp

clean:
	rm -f bmp2gbtile *~*



